apiVersion: apps/v1
kind: Deployment
metadata:
  name: buy-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smbuy
  template:
    metadata:
      labels:
        app: smbuy
    spec:
      containers:
        - name: smbuy
          image: social_media/buy:0.1
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: socialmedia
            - name: NODE_ENV
              value: 'dev'
            - name: PORT
              value: '3000'
            - name: USER_PG
              value: 'postgres'
            - name: HOST_PG
              value: 'buy-psql-srv'
            - name: PORT_PG
              value: '5432'
            - name: DB_PG
              value: 'social_media'
            - name: PSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: psql-pass
                  key: PSQL_PASS
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-social-media
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: smbuy-srv
spec:
  selector:
    app: smbuy
  ports:
    - name: smbuy
      protocol: TCP
      port: 3000
      targetPort: 3000
