apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-psql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-psql
  template:
    metadata:
      labels:
        app: product-psql
    spec:
      containers:
        - name: product-psql
          image: postgres:1.1
          env:
            - name: POSTGRES_PASSWORD
              value: '123.'
            - name: POSTGRES_DB
              value: social_media
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: product-postgres-pvc
      volumes:
        - name: product-postgres-pvc
          persistentVolumeClaim:
            claimName: product-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: product-psql-srv
spec:
  selector:
    app: product-psql
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
